name: Continous Integration
on: [pull_request]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install modules
        run: bun install
      - name: Run tests
        run: bun test
